workspace:
  base: /go

pipeline:

  test:
    image: golang:1.9
    environment:
      - CGO_ENABLED=0
    commands:
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.revision=$(git rev-parse HEAD)" -a

  build-container:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: jonathanio/drone-terraform
    auto_tag: true
    when:
      branch: master
